import type { EquipmentDefinition, GearDefinition, WeaponDefinition } from './types.js';

export const NATURAL_WEAPONS: readonly WeaponDefinition[] = [
  {
    id: 'wolf-claw-main',
    name: '狼爪',
    slot: 'mainHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [7, 13],
    balance: 0.5,
    interval: 1.05,
    range: 62,
    arc: (Math.PI * 82) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.05,
    blockRate: 0.06,
  },
  {
    id: 'wolf-claw-off',
    name: '副狼爪',
    slot: 'offHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [5, 10],
    balance: 0.52,
    interval: 1,
    range: 58,
    arc: (Math.PI * 76) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.04,
    blockRate: 0.05,
  },
  {
    id: 'elite-wolf-claw-main',
    name: '精銳狼爪',
    slot: 'mainHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [11, 18],
    balance: 0.52,
    interval: 1.1,
    range: 66,
    arc: (Math.PI * 84) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.07,
    blockRate: 0.08,
  },
  {
    id: 'elite-wolf-claw-off',
    name: '副精銳狼爪',
    slot: 'offHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [8, 14],
    balance: 0.53,
    interval: 1.05,
    range: 62,
    arc: (Math.PI * 78) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.06,
    blockRate: 0.07,
  },
  {
    id: 'alpha-claw-main',
    name: '首領巨爪',
    slot: 'mainHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [18, 30],
    balance: 0.48,
    interval: 1.45,
    range: 82,
    arc: (Math.PI * 96) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.08,
    blockRate: 0.1,
  },
  {
    id: 'alpha-claw-off',
    name: '副首領巨爪',
    slot: 'offHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [14, 24],
    balance: 0.5,
    interval: 1.25,
    range: 76,
    arc: (Math.PI * 88) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.07,
    blockRate: 0.09,
  },
  {
    id: 'blood-claw-main',
    name: '血爪',
    slot: 'mainHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [8, 15],
    balance: 0.58,
    interval: 0.95,
    range: 60,
    arc: (Math.PI * 82) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.08,
    blockRate: 0.04,
  },
  {
    id: 'blood-claw-off',
    name: '副血爪',
    slot: 'offHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [6, 12],
    balance: 0.58,
    interval: 0.9,
    range: 56,
    arc: (Math.PI * 76) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.07,
    blockRate: 0.03,
  },
  {
    id: 'noble-blood-fang',
    name: '貴族血牙',
    slot: 'mainHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [20, 34],
    balance: 0.56,
    interval: 1.6,
    range: 72,
    arc: (Math.PI * 88) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.06,
    blockRate: 0.04,
  },
  {
    id: 'noble-blood-claw-off',
    name: '副貴族血爪',
    slot: 'offHand',
    twoHanded: false,
    kind: '近戰',
    attackMode: 'melee',
    damage: [12, 22],
    balance: 0.56,
    interval: 1.15,
    range: 66,
    arc: (Math.PI * 80) / 180,
    strApplies: true,
    agiApplies: true,
    dexAmp: true,
    parryRate: 0.07,
    blockRate: 0.04,
  },
];

export const NATURAL_GEAR: readonly GearDefinition[] = [
  { id: 'wolf-hide', name: '厚毛皮', slot: 'body', armor: 1, reductionRate: 0.02, parryRate: 0, blockRate: 0 },
  { id: 'elite-wolf-hide', name: '精銳厚毛皮', slot: 'body', armor: 2, reductionRate: 0.04, parryRate: 0, blockRate: 0 },
  { id: 'alpha-hide', name: '首領厚毛皮', slot: 'body', armor: 3, reductionRate: 0.06, parryRate: 0, blockRate: 0 },
  { id: 'vampire-body', name: '吸血鬼體質', slot: 'body', armor: 1, reductionRate: 0.03, parryRate: 0.02, blockRate: 0 },
  { id: 'ancient-vampire-body', name: '古老吸血鬼體質', slot: 'body', armor: 3, reductionRate: 0.08, parryRate: 0.03, blockRate: 0 },
];

export const NATURAL_EQUIPMENT: readonly EquipmentDefinition[] = [...NATURAL_WEAPONS, ...NATURAL_GEAR];
