import type { EnemyDefinition } from './types.js';

export const ENEMY_CATALOG: Record<string, EnemyDefinition> = {
  redScout: {
    id: 'redScout',
    name: '赤色斥候',
    kind: 'meleeEnemy',
    attrs: { str: 8, vit: 8, agi: 8, dex: 8, wil: 6, luk: 6 },
    radius: 16,
    color: 0xe0564b,
    speed: 86,
    alertRange: 147,
    leashRange: 260,
    armor: 0,
    reductionRate: 0,
    parryRate: 0,
    blockRate: 0,
    loadout: {
      mainHand: 'iron-sword',
      offHand: 'wooden-shield',
      head: 'leather-cap',
      body: 'leather-armor',
      legs: 'leather-pants',
      feet: 'leather-boots',
    },
  },
  orangeGuard: {
    id: 'orangeGuard',
    name: '橙色守衛',
    kind: 'meleeEnemy',
    attrs: { str: 11, vit: 12, agi: 6, dex: 8, wil: 8, luk: 5 },
    radius: 16,
    color: 0xe0954b,
    speed: 78,
    alertRange: 140,
    leashRange: 267,
    armor: 1,
    reductionRate: 0,
    parryRate: 0,
    blockRate: 0,
    loadout: {
      mainHand: 'greatsword',
      offHand: null,
      head: 'iron-helm',
      body: 'iron-armor',
      legs: 'iron-greaves',
      feet: 'iron-boots',
    },
  },
  purpleShooter: {
    id: 'purpleShooter',
    name: '紫色射手',
    kind: 'rangedEnemy',
    attrs: { str: 7, vit: 7, agi: 10, dex: 12, wil: 10, luk: 8 },
    radius: 14,
    color: 0xb04bd9,
    speed: 62,
    preferredRange: 170,
    alertRange: 173,
    leashRange: 287,
    armor: 0,
    reductionRate: 0,
    parryRate: 0,
    blockRate: 0,
    loadout: {
      mainHand: 'hunting-bow',
      offHand: null,
      head: 'leather-cap',
      body: 'leather-armor',
      legs: 'leather-pants',
      feet: 'leather-boots',
    },
  },
  goblin: {
    id: 'goblin',
    name: '哥布林',
    kind: 'meleeEnemy',
    attrs: { str: 10, vit: 9, agi: 9, dex: 8, wil: 2, luk: 7 },
    radius: 14,
    color: 0x58a65c,
    speed: 92,
    alertRange: 127,
    leashRange: 240,
    armor: 0,
    reductionRate: 0,
    parryRate: 0,
    blockRate: 0,
    loadout: {
      mainHand: 'dagger',
      offHand: null,
      head: null,
      body: 'leather-armor',
      legs: 'leather-pants',
      feet: 'leather-boots',
    },
  },
  goblinKing: {
    id: 'goblinKing',
    name: '哥布林王',
    kind: 'meleeEnemy',
    attrs: { str: 32, vit: 36, agi: 14, dex: 14, wil: 7, luk: 11 },
    radius: 19,
    color: 0x2f7f43,
    speed: 76,
    alertRange: 160,
    leashRange: 280,
    armor: 1,
    reductionRate: 0.02,
    parryRate: 0,
    blockRate: 0,
    loadout: {
      mainHand: 'iron-sword',
      offHand: 'wooden-shield',
      head: 'iron-helm',
      body: 'iron-armor',
      legs: 'iron-greaves',
      feet: 'iron-boots',
    },
  },
  werewolf: {
    id: 'werewolf',
    name: '狼人',
    kind: 'meleeEnemy',
    attrs: { str: 16, vit: 13, agi: 16, dex: 8, wil: 2, luk: 5 },
    radius: 17,
    color: 0x8a8072,
    speed: 112,
    alertRange: 167,
    leashRange: 307,
    armor: 0,
    reductionRate: 0,
    parryRate: 0.03,
    blockRate: 0,
    loadout: {
      mainHand: 'wolf-claw-main',
      offHand: 'wolf-claw-off',
      head: null,
      body: 'wolf-hide',
      legs: null,
      feet: null,
    },
  },
  eliteWerewolf: {
    id: 'eliteWerewolf',
    name: '菁英狼人',
    kind: 'meleeEnemy',
    attrs: { str: 28, vit: 23, agi: 23, dex: 11, wil: 3, luk: 5 },
    radius: 18,
    color: 0xa08765,
    speed: 118,
    alertRange: 187,
    leashRange: 333,
    armor: 1,
    reductionRate: 0.01,
    parryRate: 0.04,
    blockRate: 0,
    loadout: {
      mainHand: 'elite-wolf-claw-main',
      offHand: 'elite-wolf-claw-off',
      head: null,
      body: 'elite-wolf-hide',
      legs: null,
      feet: null,
    },
  },
  werewolfLeader: {
    id: 'werewolfLeader',
    name: '狼人首領',
    kind: 'meleeEnemy',
    attrs: { str: 45, vit: 45, agi: 25, dex: 14, wil: 4, luk: 7 },
    radius: 21,
    color: 0x6f5d4d,
    speed: 104,
    alertRange: 200,
    leashRange: 360,
    armor: 2,
    reductionRate: 0.03,
    parryRate: 0.05,
    blockRate: 0,
    loadout: {
      mainHand: 'alpha-claw-main',
      offHand: 'alpha-claw-off',
      head: null,
      body: 'alpha-hide',
      legs: null,
      feet: null,
    },
  },
  vampireBride: {
    id: 'vampireBride',
    name: '吸血鬼新娘',
    kind: 'meleeEnemy',
    attrs: { str: 14, vit: 14, agi: 17, dex: 18, wil: 8, luk: 6 },
    radius: 15,
    color: 0xb55a78,
    speed: 96,
    alertRange: 167,
    leashRange: 307,
    armor: 0,
    reductionRate: 0.01,
    parryRate: 0.05,
    blockRate: 0,
    loadout: {
      mainHand: 'blood-claw-main',
      offHand: 'blood-claw-off',
      head: null,
      body: 'vampire-body',
      legs: null,
      feet: null,
    },
  },
  vampireLord: {
    id: 'vampireLord',
    name: '吸血鬼領主',
    kind: 'meleeEnemy',
    attrs: { str: 43, vit: 47, agi: 32, dex: 32, wil: 18, luk: 7 },
    radius: 22,
    color: 0x9d244f,
    speed: 92,
    alertRange: 213,
    leashRange: 373,
    armor: 2,
    reductionRate: 0.04,
    parryRate: 0.06,
    blockRate: 0,
    loadout: {
      mainHand: 'noble-blood-fang',
      offHand: 'noble-blood-claw-off',
      head: null,
      body: 'ancient-vampire-body',
      legs: null,
      feet: null,
    },
  },
  civilian: {
    id: 'civilian',
    name: '路人 NPC',
    kind: 'meleeEnemy',
    attrs: { str: 1, vit: 5, agi: 2, dex: 2, wil: 4, luk: 2 },
    radius: 13,
    color: 0xb8b2a5,
    speed: 58,
    alertRange: 0,
    leashRange: 200,
    armor: 0,
    reductionRate: 0,
    parryRate: 0,
    blockRate: 0,
    loadout: {
      mainHand: 'dagger',
      offHand: null,
      head: null,
      body: null,
      legs: null,
      feet: null,
    },
  },
  vampireHunter: {
    id: 'vampireHunter',
    name: '吸血鬼獵人',
    kind: 'rangedEnemy',
    attrs: { str: 14, vit: 12, agi: 12, dex: 14, wil: 4, luk: 4 },
    radius: 16,
    color: 0x4e86c6,
    speed: 86,
    preferredRange: 180,
    alertRange: 193,
    leashRange: 333,
    armor: 1,
    reductionRate: 0.02,
    parryRate: 0.02,
    blockRate: 0,
    loadout: {
      mainHand: 'pistol',
      offHand: 'revolver',
      head: 'leather-cap',
      body: 'leather-armor',
      legs: 'leather-pants',
      feet: 'leather-boots',
    },
  },
};

export function enemyById(id: string): EnemyDefinition {
  const enemy = ENEMY_CATALOG[id];
  if (!enemy) throw new Error(`Unknown enemy: ${id}`);
  return enemy;
}
